blog/user_accounts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, BooleanField
from wtforms.validators import DataRequired, Email, EqualTo, Length
from wtforms import ValidationError
from blog.model import User


class LoginForm(FlaskForm):
    email = StringField('Email', validators=[DataRequired(
        message='Email is required field'), Email(message='Email not valid')])
    password = PasswordField('Password', validators=[
                             DataRequired(message='Password is required field')])
    remember_me = BooleanField(label="Remember me", default=True)
    submit = SubmitField('Log In')


class RegistrationForm(FlaskForm):
    email = StringField('Email', validators=[DataRequired(message='Email is required field'),
                                             Email(message='Email not valid'),
                                             Length(min=4, max=200, message='Email should be between 4-200 character long')])
    username = StringField('Username', validators=[DataRequired(message='Username is required field'),
                                                   Length(min=2, max=30, message='Username should be between 2-30 character long')])
    password = PasswordField('Password', validators=[DataRequired(message='Password is required field'),
                                                     EqualTo(
                                                         'pass_confirm', message='Passwords Must Match!'),
                                                     Length(min=6, max=200, message='Password should be between 6-200 characters long')])
    pass_confirm = PasswordField('Confirm password', validators=[
                                 DataRequired(message='Confirm Password is required field')])
    remember_me = BooleanField(label="Remember me", default=True)
    submit = SubmitField('Register!')

    def validate_email(self, email):
        # For verifying email is unique
        if User.query.filter_by(email=self.email.data).first():
            raise ValidationError('Email has been registered')

    def validate_username(self, username):
        # For verifying password is unique
        if User.query.filter_by(username=self.username.data).first():
            raise ValidationError('Username has been registered')
        # For not allowing special character in username
        excluded_chars = " *?!'^+%&/()=}][{$#@"
        for char in self.username.data:
            if char in excluded_chars:
                raise ValidationError(f'"{char}" is not allowed in username')


class ResetRequest(FlaskForm):
    email = StringField('Email', validators=[DataRequired(
        message='Email is required field'), Email(message='Email not valid')])
    submit = SubmitField('Reset Password')

    def validate_email(self, email):
        user = User.query.filter_by(email=self.email.data).first()
        if user is None:
            raise ValidationError(
                'Email not yet registered. Please register email first.')


class ResetPassword(FlaskForm):
    password = PasswordField('Password', validators=[DataRequired(message='Password is required field'),
                                                     EqualTo(
                                                         'pass_confirm', message='Passwords Must Match!'),
                                                     Length(min=6, max=200, message='Password should be between 6-200 characters long')])
    pass_confirm = PasswordField('Confirm password', validators=[
                                 DataRequired(message='Confirm Password is required field')])
    submit = SubmitField('Reset Password')


class OTPForm(FlaskForm):
    otp = StringField(label='OTP', validators=[
                      DataRequired(), Length(min=6, max=6, message='Invalid OTP')])
    submit = SubmitField('Register')

blog/user_accounts/views.py
from flask import Blueprint, render_template, redirect, url_for, flash, request
from blog.model import User
from blog import db, app
from blog.user_accounts.forms import RegistrationForm, LoginForm, ResetRequest, ResetPassword, OTPForm
from flask_login import login_user, login_required, logout_user, current_user
from werkzeug.security import generate_password_hash
from blog.user_accounts.email_validation import send_reset_email, send_verification_email

user_account_blueprint = Blueprint('user_accounts',
                                   __name__,)


@user_account_blueprint.route('/register/', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        email = form.email.data
        password = form.password.data
        username = form.username.data
        user = User(username, password, email)
        otp = send_verification_email(user)
        token = user.get_verification_token(otp=otp)
        return redirect(url_for('user_accounts.otp_verification', token=token, remember_me=form.remember_me.data))

    return render_template('user_accounts/register.html', form=form)


@user_account_blueprint.route('/verify_email/<token>', methods=['GET', 'POST'])
def otp_verification(token):
    if current_user.is_authenticated:
        return redirect(url_for('home'))
    # Token Processing
    user, otp = User.verify_verification_token(token)
    remember_me = request.args.get('remember_me')
    remember_me = True if remember_me == 'True' else False
    if user is None or otp is None:
        flash('Invalid or expired token')
        return redirect(url_for('user_accounts.login'))

    # Validate OTP
    form = OTPForm()
    if form.validate_on_submit():
        if not form.otp.data == str(otp):
            flash('Invalid OTP')
            return redirect(url_for('user_accounts.otp_verification', token=token))
        db.session.add(user)
        db.session.commit()
        login_user(user, remember=remember_me)
        return redirect(url_for('home'))
    return render_template('user_accounts/otp_verification.html', form=form)


@user_account_blueprint.route('/logout/')
@login_required
def logout():
    logout_user()
    return redirect(url_for('user_accounts.login'))


@user_account_blueprint.route('/login/', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('home'))
    form = LoginForm()
    if form.validate_on_submit():
        email = form.email.data
        password = form.password.data
        user = User.query.filter_by(email=email).first()
        if user is not None and user.check_password(password):
            login_user(user, remember=form.remember_me.data)
            next_ = request.args.get('next')
            if next_ == None or not next_[0] == '/':
                next_ = url_for('home')

            return redirect(next_)
        else:
            flash("Incorrect email or password", 'danger')
    return render_template('user_accounts/login.html', form=form)


@user_account_blueprint.route('reset_password', methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('home'))
    form = ResetRequest()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('Password reset link has been sent to the provided email.', 'info')
        return redirect(url_for('user_accounts.login'))
    return render_template('user_accounts/reset_request.html', form=form)


@user_account_blueprint.route('reset_password/<token>', methods=['GET', 'POST'])
def reset_password(token):
    if current_user.is_authenticated:
        return redirect(url_for('home'))
    user = User.verify_token(token)
    if user is None:
        flash('The token was invalid or experied.')
        return redirect(url_for('user_accounts.login'))
    form = ResetPassword()
    if form.validate_on_submit():
        user.password = generate_password_hash(form.password.data)
        db.session.commit()
        flash('Password reset successful! You could login now.', 'info')
        return redirect(url_for('user_accounts.login'))
    return render_template('user_accounts/reset_password.html', form=form)

blog/templates/user_accounts/login.html
{% extends 'base.html' %}
{% from 'macros.html' import render_field %}
{% set active_page = "login" %}
{% block content %}
<h1 class="display-5 mt-2 mb-3">Login</h1>
{% with messages = get_flashed_messages(with_categories=true) %}
{% if messages %}
{% for category, message in messages %}
<div class="alert {% if category=='message' %}alert-warning{% else %}alert-{{category}}{% endif %}">
    {{ message }}
</div>
{% endfor %}
{% endif %}
{% endwith %}
<form action="" method="POST">
    {{ form.hidden_tag() }}
    {{ render_field(form.email,ph = "example@example.com") }}
    {{ render_field(form.password,ph = "Password") }}
    <div class="form-check mb-3">
        {{ form.remember_me(class='form-check-input') }}
        {{ form.remember_me.label(class='form-check-label') }}
    </div>
    {{ form.submit(class='btn btn-outline-success') }}
    <a href="{{url_for('user_accounts.reset_request')}}" class="link-primary">Forgot Password?</a>
</form>
{% endblock %}

blog/templates/user_accounts/otp_verification.html
{% extends 'base.html' %}
{% from 'macros.html' import render_field %}
{% block content %}
<h1 class="display-5">OTP Verification</h1>
{% if get_flashed_messages() %}
{% for mess in get_flashed_messages() %}
<div class="alert alert-danger" role="alert">
    {{mess}}
</div>

{% endfor %}
{% endif %}
<form action="" method="post">
    {{form.hidden_tag()}}
    {{render_field(form.otp,ph='OTP',mt='An OTP has been sent to the provided email. Please enter otp to continue')}}
    {{form.submit(class = 'btn btn-outline-success')}}
</form>
{% endblock %}

blog/templates/user_accounts/register.html
{% extends 'base.html' %}
{% from 'macros.html' import render_field %}
{% set active_page = "register" %}
{% block content %}
<h1 class="display-5 mt-2 mb-3">Register</h1>

<form action="" method="POST">
    {{ form.hidden_tag() }}
    {{ render_field(form.username,ph = "Username", mt="Should be betweem 2-30 character long and not contain any special
    character") }}
    {{ render_field(form.email,ph = "example@example.com") }}
    {{ render_field(form.password,ph = "Password",mt="Should be between 6-200 character long") }}
    {{ render_field(form.pass_confirm,ph = "Confirm Password", mt="Repeat password") }}
    <div class="form-check mb-3">
        {{ form.remember_me(class='form-check-input') }}
        {{ form.remember_me.label(class='form-check-label') }}
    </div>
    {{ form.submit(class='btn btn-outline-success') }}
    <a href="{{ url_for('user_accounts.login') }}" class="ms-md-3 link-primary"><span
            class="d-none d-md-inline-block link-primary">Already have an account?&nbsp;&nbsp;</span>Login</a>
</form>
{% endblock %}

blog/templates/user_accounts/reset_password.html
{% extends 'base.html' %}
{% from 'macros.html' import render_field %}
{% block content %}
<h1 class="display-5">Reset Password</h1>

<form action="" method="post">
    {{form.hidden_tag()}}
    {{ render_field(form.password,ph = "New Password",mt="Should be between 6-200 character long") }}
    {{ render_field(form.pass_confirm,ph = "Confirm Password", mt="Repeat password") }}
    {{form.submit(class = 'btn btn-outline-success')}}</form>
{% endblock %}

blog/templates/user_accounts/reset_request.html
{% extends 'base.html' %}
{% from 'macros.html' import render_field %}
{% block content %}
<h1 class="display-5">Reset Password</h1>
<form action="" method="post">
    {{ form.hidden_tag() }}
    {{ render_field(form.email,ph = "example@example.com") }}
    {{ form.submit(class='btn btn-outline-success') }}
</form>
{% endblock %}