blog/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,TextAreaField,SubmitField
from wtforms.validators import DataRequired,Length

class AddPost(FlaskForm):
    title = StringField(label='Title',validators=[DataRequired(),Length(min=5,max=128)])
    short_description = StringField(label='Short Description',
                                    validators=[DataRequired(),Length(min=5,max=250)])
    post = TextAreaField(label='Post Content',
                        validators=[Length(min=100, max=10000)],
                        render_kw={'rows':16})

    submit = SubmitField('Post')
class DeletePost(FlaskForm):
    submit = SubmitField('Delete Post')

blog/posts/views.py
from flask import Blueprint, render_template, redirect, url_for, flash, abort, request
from blog.posts.forms import AddPost, DeletePost
from blog.model import Post
from blog import db, app
from flask_login import login_required, current_user
posts_blueprint = Blueprint('posts',
                            __name__,)


@posts_blueprint.route('/add/', methods=['GET', 'POST'])
@login_required
def add():
    form = AddPost()
    if form.validate_on_submit():
        post = Post(current_user.id,
                    form.title.data,
                    form.post.data,
                    form.short_description.data)
        db.session.add(post)
        db.session.commit()
        return redirect(url_for('home'))
    return render_template('posts/add_post.html', form=form, title='Add Post')


@posts_blueprint.route('/<int:post_id>/')
def single_post(post_id):
    post = Post.query.get_or_404(post_id)
    form = DeletePost()
    return render_template('posts/single_post.html', post=post, form=form)


@posts_blueprint.route('/<int:post_id>/update', methods=['GET', 'POST'])
@login_required
def update_post(post_id):
    form = AddPost()
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)

    if form.validate_on_submit():
        post.title = form.title.data
        post.short_description = form.short_description.data
        post.post = form.post.data
        db.session.commit()
        return redirect(url_for('posts.single_post', post_id=post_id))
    elif request.method == 'GET':
        form.title.data = post.title
        form.short_description.data = post.short_description
        form.post.data = post.post
    return render_template('posts/add_post.html', form=form, title='Edit Post')


@posts_blueprint.route('/<int:post_id>/delete', methods=['POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    return redirect(url_for('home'))

blog/profile/views.py
from flask import Blueprint, render_template, redirect, url_for, flash, request, abort
from blog.model import User, Post
from blog import db, app
from flask_login import login_required, current_user
from blog.profile.forms import UpdateForm, ChangePassword
import secrets
import os
from PIL import Image
from PIL import UnidentifiedImageError
from werkzeug.security import generate_password_hash
profile_blueprint = Blueprint('profile',
                              __name__,)


def save_image(profile_pic):
    random_hex = secrets.token_hex(8)
    _, f_ext = os.path.splitext(profile_pic.filename)
    picture_fn = random_hex + f_ext
    picture_path = os.path.join(
        app.root_path, 'static/profile_pic', picture_fn)
    # There is no point in storing really large images in file system
    # In the end they are going to be scaled down by css
    # Storing large images would cause the website to slow down as it have to download larger images

    output_size = (125, 125)
    try:
        i = Image.open(profile_pic)
    except UnidentifiedImageError:
        raise UnidentifiedImageError()
    i.thumbnail(output_size)
    i.save(picture_path)

    return picture_fn


def delete_bloat():
    if current_user.image_file == 'default.jpg':
        return
    picture_path = os.path.join(
        app.root_path, 'static/profile_pic', current_user.image_file)
    os.remove(picture_path)


@profile_blueprint.route('/account_info/', methods=['GET', 'POST'])
@login_required
def update_account():
    form = UpdateForm()
    if form.validate_on_submit():
        if form.profile_pic.data:
            try:
                picture_file = save_image(form.profile_pic.data)
            except UnidentifiedImageError:
                flash('Invalid image file provided', 'danger')
                return redirect(url_for('profile.update_account'))
            delete_bloat()
            current_user.image_file = picture_file
            db.session.commit()
        current_user.username = form.username.data
        db.session.commit()
        flash('Your account info has been updated successfully!', 'success')
        return redirect(url_for('profile.update_account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
    username = current_user.username
    email = current_user.email
    profile_pic = url_for(
        'static', filename=f'profile_pic/{current_user.image_file}')
    return render_template('profile/edit_profile.html', profile_pic=profile_pic,
                           email=email, username=username, form=form)


@profile_blueprint.route('/change_password/', methods=['GET', 'POST'])
@login_required
def change_password():
    form = ChangePassword()
    if form.validate_on_submit():
        current_user.password = generate_password_hash(form.new_password.data)
        db.session.commit()
        flash('Password changed successfully.', 'info')
        return redirect(url_for('profile.change_password'))
    return render_template('profile/change_password.html', form=form)


@profile_blueprint.route('/<username>/')
def user_posts(username):
    page = request.args.get('page', type=int)
    user = User.query.filter_by(username=username).first_or_404()
    posts = Post.query.filter_by(user_id=user.id).order_by(
        Post.date.desc()).paginate(per_page=5, page=page)
    return render_template('profile/profile_page.html', username=user.username, posts=posts, email=user.email,
                           profile_pic=url_for(
                               'static', filename=f'profile_pic/{user.image_file}'),
                           profile=True)

blog/templates/posts/_paginate.html
<nav>
  <ul class="pagination">

    <li class="page-item {% if posts.has_prev == False%} disabled {% endif %}">
      <a class="page-link"
        href="{% if profile %}{{url_for('profile.user_posts',username=username,page=posts.page-1)}}{% else %}{{url_for('home',page=posts.page-1)}}{% endif %}"
        aria-label="Next">

        <span aria-hidden="true">&laquo;</span>
      </a>
    </li>
    {% if posts.has_prev %}
    <li class="page-item"><a class="page-link"
        href="{% if profile %}{{url_for('profile.user_posts',username=username,page=posts.page-1)}}{% else %}{{url_for('home',page=posts.page-1)}}{% endif %}">{{posts.page-1}}</a>
    </li>
    {% endif %}
    <li class="page-item active"><a class="page-link" href="#">{{posts.page}}</a></li>
    {% if posts.has_next %}
    <li class="page-item"><a class="page-link"
        href="{% if profile %}{{url_for('profile.user_posts',username=username,page=posts.page+1)}}{% else %}{{url_for('home',page=posts.page+1)}}{% endif %}">{{posts.page+1}}</a>
    </li>
    {% endif %}
    <li class="page-item {% if posts.has_next == False%} disabled {% endif %}">
      <a class="page-link"
        href="{% if profile %}{{url_for('profile.user_posts',username=username,page=posts.page+1)}}{% else %}{{url_for('home',page=posts.page+1)}}{% endif %}"
        aria-label="Next">
        <span aria-hidden="true">&raquo;</span>
      </a>
    </li>
  </ul>
</nav>

blog/templates/posts/_posts.html
{% for post in posts.items %}
<article class="media content-section">
  <div class="row">
    <div class="col-lg-1 col-2 d-none d-sm-block">
      <img class="rounded-circle article-img"
        src="{{ url_for('static', filename='profile_pic/' + post.author.image_file) }}">
    </div>
    <div class="col">
      <div class="media-body">
        <div class="article-metadata">
          <a class="mr-2" href="{{url_for('profile.user_posts',username = post.author.username)}}">
            {{ post.author.username }}
          </a>
          <small class="text-muted">{{ post.date|human_date }}</small>
        </div>
        <h2><a class="article-title" href="{{url_for('posts.single_post',post_id=post.id)}}">{{ post.title }}</a></h2>
        <p class="article-content">{{ post.short_description }}</p>
      </div>
    </div>
  </div>
</article>
{% endfor %}

blog/templates/posts/add_post.html
{% set active_page='add' %}
{% extends 'base.html' %}
{% from 'macros.html' import render_field %}
{% block content %}
<script src="https://cdn.tiny.cloud/1/uptfl2jnbjyn9klw3v64xkjsuy2t8vn45cwa8cu7ioegarcp/tinymce/5/tinymce.min.js"
    referrerpolicy="origin"></script>
<h1 class="display-5">{{title}}</h1>

<form action="" method="post" class="form">
    {{ form.hidden_tag() }}
    {{ render_field(form.title,ph = "Title") }}
    {{ render_field(form.short_description,ph = "Short Description") }}
    {{ render_field(form.post) }}


    {{ form.submit(class='btn btn-outline-success') }}
</form>
<script src="{{url_for('static',filename='js/main.js')}}"></script>



{% endblock %}

blog/templates/posts/index.html
{% set active_page = "home" %}
{% extends 'base.html' %}
{% block content %}
<form>
    <div class="input-group mb-3 mt-2 mb-2">

        <input type="text" class="form-control" placeholder="Search Posts" aria-label="Search" name="search"
            value="{% if search_term %}{{search_term}}{% endif %}">
        <button class="fas fa-search input-group-text" type="submit"></button>
    </div>
</form>
{% if posts %}
{% if search_term %}
<p class="lead text-muted">Search Results For : {{search_term}}</p>
{% endif %}
{% include 'posts/_posts.html' %}
{% else %}
{% if search_term %}
<p class="lead text-muted">No post available for query : {{search_term}}</p>
{%else%}
<p class="lead text-muted">No post available at the moment</p>
{% endif %}

{% endif %}

{% include 'posts/_paginate.html' %}
<script src="https://kit.fontawesome.com/cb2a19a906.js" crossorigin="anonymous"></script>

{% endblock %}

blog/templates/posts/single_post.html
{% extends "base.html" %}
{% block content %}
<link rel="stylesheet" href="{{url_for('static',filename='css/prism.css')}}">
<article class="media content-section">
  <img class="rounded-circle article-img"
    src="{{ url_for('static', filename='profile_pic/' + post.author.image_file) }}">
  <div class="media-body">
    <div class="article-metadata">
      <a class="mr-2" href="{{url_for('profile.user_posts',username = post.author.username)}}">{{ post.author.username
        }}</a>
      <small class="text-muted">{{ post.date.strftime('%Y-%m-%d') }}</small>
      {% if post.author == current_user %}
      <div>
        <a class="btn btn-secondary btn-sm mt-1 mb-1"
          href="{{ url_for('posts.update_post', post_id=post.id) }}">Update</a>
        <button type="button" class="btn btn-danger btn-sm m-1" data-bs-toggle="modal"
          data-bs-target="#deleteModal">Delete</button>
      </div>
      {% endif %}
    </div>
    <h2 class="article-title">{{ post.title }}</h2>
    <p class="article-content">{{ post.post|safe }}</p>
  </div>
</article>
<script src="{{url_for('static',filename='js/prism.js')}}"></script>
<!-- Modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="deleteModalLabel">Delete Post?</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>

      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <form action="{{url_for('posts.delete_post',post_id=post.id)}}" method="POST">
          {{form.hidden_tag()}}
          {{form.submit(class='btn btn-danger')}}
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}